# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    initial = True
